### ISSUE TITLE
Acyclic check fails on larger model

### ISSUE THREAD

**Issue by orfisko** [chrisspen/criticalpath#3]
When sending a relatively large model containing about 370 links the code fails to pass through the is acyclic check. When commenting this line out I also don't get to completion and all RAM memory will in the end be consumed by the process. I can supply the inputs I am modelling upon request. 
When removing just a couple of links that are positioned at the very beginning of the dependency chain I am able to get to a solution. 
A potential solution to this could be to optimise first between 'intersections' of paths and then use those results to solve the global problem.

**Comment by orfisko** [comment]
I have created a test case so that you can easily replay the issue. 
The zip contains:
- timings: these I am feeding as the node duration
- deps: all dependencies. I have included a working and a non working set. If I feed the working one in the code it takes about a minute on my machine to calculate the critical path
- criticalpath.py: this is the cod you put on github. I have removed the unittest and put some code in to load the input files. The logic for adding dependencies is there to add a node in case a dependency is being added for a node which was not created when iterating through the timings file.
[issue_files.zip](https://github.com/chrisspen/criticalpath/files/2148377/issue_files.zip)

**Comment by orfisko** [comment]
Please find attached two PDFS created with graphviz to show how the model looks like. 

[not_working.pdf](https://github.com/chrisspen/criticalpath/files/2148420/not_working.pdf)
[working.pdf](https://github.com/chrisspen/criticalpath/files/2148421/working.pdf)

The working version builds up the main tree from node 1266 onwards. The non working version also includes precedents to node 1266.

**Comment by chrisspen** [comment]
Thanks for documenting the issue. I'll try to take a look at this, but my day job consumes most of my time, so my resources to spend on this are extremely limited. If you figure it out on your own, I'd welcome a pull request.

**Comment by chrisspen** [comment]
>When commenting this line out

What line are you referring to? Comparing the diff between your code to the original, I don't see anything commented out.

**Comment by orfisko** [comment]
Hello Chris,
The acyclic check.
Regards,
Hendrik

**Comment by chrisspen** [comment]
I see. The main difference between the working and non working versions are that you seem to have connected two large but separate graphs in the non working one. Adding graphs like that increases complexity on an exponential scale, and the result is a state explosion of possibilities that must be checked to ensure there are no acyclic paths. My algorithm to check this is thorough but not terribly sophisticated or efficient. It simply brute-force checks everything, so its performance scales exponentially. I'll look into improving this, but a lot of these type of graph problems don't have any good solutions, so I can't promise anything.

One workaround is to reduce the dimensionality by abstracting the state space. For example, instead of linking two massive graphs together, you could put all the nodes for the two graphs as children under two separate nodes, abstracting them as individual parent tasks. That would reduce a potentially O(N*N) problem to a O(2) problem, which the code should be able to handle easily. Ideally, the code should be able to automatically handle some of those situations, but until it does, that would be the alternative.

**Comment by orfisko** [comment]
Thanks Chris. I have been considering that workaround.  The problem is that the model I am feeding changes relatively frequent (every two weeks or so), and I would prefer not needing to analyse the structure of the network and group blocks in the graph together before modelling the network with your code. If I would need to figure this out myself, I would have to apply methods similar to the ones you have created. 
A different solution could perhaps be relatively straightforward by having the network scanned for any subsections like the one between 1014 and 1064 for example. You could consider to use a variable that can steer the number of priors to an intersection node like 1064 to scan and try to find common node 1014 for all paths between them. If you would set that to 10, I think the complexity of the model would be greatly reduced.
Once that is done the optimisation of the global model comes down to adding the calculated earliest start time of grouped  1014-1064 nodes to the earliest finish of 2413 whilst applying the logic you have already built, essentially abstracting from all paths in between those two nodes.
Perhaps also good to know is that I personally only care about the earliest start time.

**Comment by chrisspen** [comment]
I think I've found a solution. I found an graph search algorithm that's more efficient than my previous DFS algorithm, and although your non-working graph still takes a while to check, it completes on my 2.8 GHz quad core machine with 32GB in about 10 minutes, whereas the previous one would have taken hours. It seemed to consume a huge amount of memory too, but this one doesn't appear to use more than 5%.

Do you mind if I use your dsv files and code as part of a unittest?

**Comment by orfisko** [comment]
That is great news. Feel free to go ahead.

**Comment by chrisspen** [comment]
I've uploaded the new version to PyPI. Let me know if this resolves the issue.
